/* GEDEP — ficha pessoal compartilhada entre módulos */
(function(){
  'use strict';
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'})[c];});}
  function norm(v){return String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]/g,'');}
  function data(){try{return typeof appData!=='undefined'?appData:(window.appData||{});}catch(e){return window.appData||{};}}
  function findRecord(mod,id){
    id=decodeURIComponent(String(id));var d=data();
    if(mod==='rh' && id.indexOf('__rhidx:')===0){var idx=Number(id.slice(8));return (d.records||[])[idx]||null;}
    if(mod==='rh') return (d.records||[]).find(function(r){return String(r.idServidor||r.id||r.CPF||r['CPF']||r['NOME SERVIDOR']||'')===String(id);});
    return (d.servidores||[]).find(function(r){return String(r.idServidor||r.id||r.cpf||'')===String(id);});
  }
  function value(r,names){var keys=Object.keys(r||{});for(var i=0;i<names.length;i++){var k=keys.find(function(x){return norm(x)===norm(names[i]);});if(k&&r[k])return r[k];}return '';}
  function ensureStyle(){if(document.getElementById('gedep-ficha-style'))return;var st=document.createElement('style');st.id='gedep-ficha-style';st.textContent='.gedep-ficha-overlay{position:fixed;inset:0;background:rgba(15,23,42,.62);z-index:9999;display:flex;align-items:center;justify-content:center;padding:18px}.gedep-ficha{background:#fff;border-radius:18px;max-width:880px;width:100%;max-height:92vh;overflow:auto;box-shadow:0 24px 70px #0005}.gedep-ficha-head{display:flex;justify-content:space-between;align-items:center;padding:18px 22px;border-bottom:1px solid #e2e8f0}.gedep-ficha-body{padding:22px}.gedep-ficha-photo{width:128px;height:128px;border-radius:18px;object-fit:cover;background:#e2e8f0}.gedep-ficha-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.gedep-ficha-field{padding:10px 12px;border:1px solid #e2e8f0;border-radius:10px;background:#f8fafc}.gedep-ficha-label{display:block;font-size:11px;text-transform:uppercase;color:#64748b;font-weight:700;margin-bottom:4px}.gedep-ficha-actions{display:flex;gap:8px;flex-wrap:wrap;padding:16px 22px;border-top:1px solid #e2e8f0}.gedep-ficha-btn{border:0;border-radius:8px;padding:9px 13px;font-weight:700;cursor:pointer}.gedep-ficha-primary{background:#2563eb;color:#fff}.gedep-ficha-danger{background:#fee2e2;color:#b91c1c}@media(max-width:640px){.gedep-ficha-grid{grid-template-columns:1fr}}';document.head.appendChild(st);}
  function close(){var e=document.getElementById('gedep-ficha-overlay');if(e)e.remove();}
  function edit(mod,id){close();if(mod==='fcpe'&&window.editarServidor)editarServidor(id);else if(mod==='cargos'&&window.editarPessoa)editarPessoa(id);else if(mod==='rh'&&window.abrirEditorServidor)abrirEditorServidor(id);}
  function remove(mod,id){if(mod==='fcpe'&&window.excluirServidor)excluirServidor(id);else if(mod==='cargos'&&window.removerPessoa)removerPessoa(id);else if(mod==='rh'&&window.excluirServidor)excluirServidor(id);close();}
  function launch(mod,id){close();if(mod==='fcpe'&&window.switchTab){switchTab('lancamentos');var s=document.getElementById('lancServidorId');if(s)s.value=id;}}
  function printCard(r){var w=window.open('','_blank','width=900,height=700');if(!w)return;w.document.write('<html><head><title>Ficha pessoal</title><style>body{font:14px Arial;padding:30px}h1{color:#1e3a8a}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.item{border:1px solid #ddd;padding:10px;border-radius:6px}img{width:130px;height:130px;object-fit:cover;border-radius:12px}</style></head><body><h1>Ficha pessoal</h1><div class="grid">'+Object.keys(r||{}).filter(function(k){return !['historico','foto','fotoUrl'].includes(k)&&typeof r[k]!=='object';}).map(function(k){return '<div class="item"><b>'+esc(k)+'</b><br>'+esc(r[k])+'</div>';}).join('')+'</div></body></html>');w.document.close();w.focus();w.print();}
  function openFicha(mod,id){ensureStyle();var r=findRecord(mod,id);if(!r)return;var nome=value(r,['nome','NOME SERVIDOR','NOME']);var photo=value(r,['foto','fotoUrl','FOTO URL']);var fields=[['Nome',nome],['CPF',value(r,['cpf','CPF'])],['Cargo',value(r,['cargo','cargoEfetivo','DESC CARGO'])],['Lotação',value(r,['lotacao','UNID ADM DE LOTAÇÃO','UNIDADE DE LOTAÇÃO'])],['FCPE',value(r,['fcpeAtual','FCPE ATUAL','VALOR'])],['Status',value(r,['statusMinuta','STATUS'])],['Ramal',value(r,['ramal','RAMAL'])],['Processos',value(r,['TOTAL_PROCESSOS','processos'])]];var overlay=document.createElement('div');overlay.id='gedep-ficha-overlay';overlay.className='gedep-ficha-overlay';overlay.innerHTML='<div class="gedep-ficha"><div class="gedep-ficha-head"><div><div style="font-size:11px;color:#64748b;font-weight:700;text-transform:uppercase">GEDEP • Ficha pessoal</div><h2 style="margin:4px 0;color:#1e3a8a">'+esc(nome||'Servidor')+'</h2></div><button class="gedep-ficha-btn" id="gedep-ficha-close">✕</button></div><div class="gedep-ficha-body"><div style="display:flex;gap:20px;align-items:flex-start;margin-bottom:18px"><div class="gedep-ficha-photo">'+(photo?'<img class="gedep-ficha-photo" src="'+esc(photo)+'">':'<div class="gedep-ficha-photo" style="display:flex;align-items:center;justify-content:center;font-size:42px;color:#94a3b8">◎</div>')+'</div><div class="gedep-ficha-grid" style="flex:1">'+fields.map(function(f){return '<div class="gedep-ficha-field"><span class="gedep-ficha-label">'+esc(f[0])+'</span>'+esc(f[1]||'Não informado')+'</div>';}).join('')+'</div></div><div class="gedep-ficha-grid">'+Object.keys(r).filter(function(k){return !fields.some(function(f){return norm(f[0])===norm(k);})&&!['historico','foto','fotoUrl','id','idServidor'].includes(k)&&typeof r[k]!=='object';}).slice(0,20).map(function(k){return '<div class="gedep-ficha-field"><span class="gedep-ficha-label">'+esc(k)+'</span>'+esc(r[k])+'</div>';}).join('')+'</div></div><div class="gedep-ficha-actions"><button class="gedep-ficha-btn gedep-ficha-primary" id="gedep-ficha-edit">Editar</button><button class="gedep-ficha-btn" id="gedep-ficha-print">Imprimir</button>'+(mod==='fcpe'?'<button class="gedep-ficha-btn" id="gedep-ficha-launch">Incluir lançamento</button>':'')+'<button class="gedep-ficha-btn gedep-ficha-danger" id="gedep-ficha-delete">Excluir</button></div></div>';document.body.appendChild(overlay);document.getElementById('gedep-ficha-close').onclick=close;document.getElementById('gedep-ficha-edit').onclick=function(){edit(mod,id);};document.getElementById('gedep-ficha-print').onclick=function(){printCard(r);};document.getElementById('gedep-ficha-delete').onclick=function(){if(confirm('Excluir este servidor?'))remove(mod,id);};var launchBtn=document.getElementById('gedep-ficha-launch');if(launchBtn)launchBtn.onclick=function(){launch(mod,id);};overlay.onclick=function(e){if(e.target===overlay)close();};}
  window.gedepAbrirFicha=openFicha;window.gedepFecharFicha=close;
})();
